SELECT ?content ?prop ?grouped ?grouped_updated ?associated ?associated_updated WHERE {
  VALUES ?prop { 
    wdt:P161
  }
  FILTER (STR(?content) < "http://www.wikidata.org/entity/Q3000000")
  ?content ?prop ?grouped.
  ?grouped wdt:P527 ?associated;
    schema:dateModified ?grouped_updated.
  ?associated schema:dateModified ?associated_updated.
}