SELECT ?item ?prop ?value ?date WHERE {
  VALUES ?prop { 
    wdt:P6932 # RogerEbert.com
    wdt:P6127 # Letterboxd
    wdt:P5384 # Behind The Voice Actors
    wdt:P5693 # Fandango
    wdt:P5865 # IGN
    wdt:P5990 # MoviesAnywhere
    wdt:P4632 # Bechdel Test Movie List
    wdt:P1712 # Metacritic
    wdt:P1562 # AllMovie
    wdt:P1258 # RottenTomatoes
    wdt:P1237 # Box Office Mojo 
    wdt:P480 # FilmAffinity
    wdt:P4086 # MyAnimeList
    wdt:P14051 # MyWaifuList Anime
    wdt:P1985 # Anime News Network
    wdt:P4933 # The Big Cartoon DataBase
    wdt:P3868 # MyDramaList
    wdt:P3808 # TheNumbers
    wdt:P3787 # danskefilm.dk Silent Films (Denmark)
    wdt:P3593 # AFI Catalog
    wdt:P3302 # Open Movie Database (Germany)
  }
  ?item ?prop ?value;
        schema:dateModified ?date.
}