SELECT ?item ?prop ?value ?date WHERE {
  VALUES ?prop { 
    wdt:P905 # PORT-network (Hungary)
    wdt:P1934 # Animator.ru (Russia)
    wdt:P2529 # Czech-Slovak film database ČSFD (Czech Republic and Slovakia)
    wdt:P2603 # Kinopoisk.ru (Russia)
    wdt:P2636 # Ministry of culture's public register of films (Russia)
    wdt:P2678 # Russiancinema.ru (Russia)
    wdt:P2826 # Megogo (Ukraine)
    wdt:P3110 # ISzDb (a Hungarian dub database) (Hungary)
    wdt:P3495 # filmpolski.pl (Poland)
    wdt:P5032 # filmweb.pl (Poland)
    wdt:P5311 # Kino-teatr.ua (Ukraine)
    wdt:P7204 # Mafab.hu (Hungary)
    wdt:P7892 # Estonian Film Database (Estonia)
    wdt:P8847 # kinorium.com (Russia and Ukraine)
    wdt:P9146 # Complete Index to World Film (www.citwf.com) (UK)
    wdt:P9203 # CineFAN.ro (Romania)
    wdt:P9204 # cinemarx.ro (Romania)
    wdt:P9283 # AaRC.ro (All About Romanian Cinema) (Romannia)
    wdt:P9461 # DzygaMDB.com (Ukraine)
    wdt:P10045 # Vokrug.tv (Russia)
    wdt:P10164 # Kinomania.ru (Russia)
    wdt:P10167 # Kinobaza.com.ua (Ukraine)
    wdt:P10255 # Okino.ua (Ukraine)
    wdt:P10267 # Kinofilms.ua (Ukraine)
    wdt:P10269 # kino-teatr.ru (Russia)
    wdt:P10303 # film.ru (Russia)
    wdt:P10769 # Kino-kolo (Ukraine)
    wdt:P10773 # Afisha (Russia)
    wdt:P10819 # Kino-Mail (Russia)
    wdt:P10821 # Kino-Mail (Russia)
    wdt:P11606 # MosFilm online (Russia)
    wdt:P11682 # Ivi.ru (Russia)
    wdt:P11687 # Kinoglaz (Russia and France)
    wdt:P11748 # Kino1TV (Russia)
    wdt:P13858 # gosfilmofond.ru (Russia)
  }
  ?item ?prop ?value;
        schema:dateModified ?date.
}