SELECT ?content ?content_updated ?credit ?credit_updated WHERE {
  ?content wdt:P750 ?credit; #distributed by
           schema:dateModified ?content_updated.
  ?credit schema:dateModified ?credit_updated.

  FILTER(xsd:integer(STRAFTER(STR(?content), "Q")) >= 20000000)
}