SELECT ?content ?content_updated ?credit ?credit_updated WHERE {
  ?content wdt:P2554 ?credit; # production designer
           schema:dateModified ?content_updated.
  ?credit schema:dateModified ?credit_updated.
}