SELECT ?content ?content_updated ?credit ?credit_updated WHERE {
  ?content wdt:P3092 ?credit; # film crew
           schema:dateModified ?content_updated.
  ?credit schema:dateModified ?credit_updated.
}