SELECT ?content ?content_updated ?credit ?credit_updated WHERE {
  ?content wdt:P1431 ?credit; # producer
           schema:dateModified ?content_updated.
  ?credit schema:dateModified ?credit_updated.
}