SELECT ?prop ?content ?content_updated ?credit ?credit_updated WHERE {
  VALUES ?prop { 
    wdt:P1809 # choreographer
    wdt:P86 # composer
    wdt:P2515 # costume designer
    wdt:P12617 # creative director
    wdt:P3092 # film crew
    wdt:P1040 # film editor
    wdt:P2554 # production designer
    wdt:P5028 # sound designer
    wdt:P344 # director of photography / cinematographer
    wdt:P1431 # executive producer
    wdt:P162 # producer
  }
  ?content ?prop ?credit;
           schema:dateModified ?content_updated.
  ?credit schema:dateModified ?credit_updated.
}