SELECT ?item ?prop ?value ?date WHERE {
  VALUES ?prop { 
    # wdt:P10275 # AsianWiki (combined, no prefix)
    wdt:P9821 # Unconsenting Media 
    wdt:P9584 # Criterion Collection website (not spine)
    wdt:P9205 # sinemalar.com (Turkey)
    wdt:P8928 # Filmstriben (Denmark)
    wdt:P8680 # Film & Video Labelling Body (New Zealand)
    wdt:P7777 # AdoroCinema (Brazil)
    wdt:P3212 # International Standard Audiovisual Number (ISAN)
    wdt:P2704 # EIDR
    wdt:P2465 # Allcinema (Japan)
    wdt:P1970 # MovieMeter (Netherlands)
  }
  ?item ?prop ?value;
        schema:dateModified ?date.
}