SELECT ?item ?prop ?value ?date WHERE {
  VALUES ?prop { 
    wdt:P6739 # Russia-1 (Russia)
    wdt:P8381 # Emmy, Academy of Television Arts & Sciences 
    wdt:P9329 # svoya-igra.org (Russia)
    wdt:P9864 # Télé-Loisirs (France)
    wdt:P10052 # Vokrug.tv (Russia)
    wdt:P10062 # Academy of Russian Television
    wdt:P10446 # Russian TV game What? Where? When? (Russia)
    wdt:P11596 # TVer (Japan)
    wdt:P12033 # France 3 Régions (France)
  }
  ?item ?prop ?value;
        schema:dateModified ?date.
}