SELECT ?p ?item ?value ?reason WHERE {
  VALUES (?p ?ps) {
    (p:P4947 ps:P4947) ## tmdb movie id
    (p:P4983 ps:P4983) ## tmdb series id
    (p:P4985 ps:P4985) ## tmdb person id
  }
  ?item ?p ?property. ## imdb id
  ?property ?ps ?value;
                 wikibase:rank wikibase:DeprecatedRank.
  OPTIONAL { ?property pq:P2241 ?reason. }
}