SELECT ?item ?prop ?value ?date WHERE {
  VALUES ?prop { 
    wdt:P4985 # tmdb person id
  }
  ?item ?prop ?value;
        schema:dateModified ?date.

  BIND(xsd:integer(STRAFTER(STR(?item), "Q")) AS ?qnum)
  FILTER(?qnum < 10000000)
}