SELECT ?p31 ?p31_updated (COUNT(DISTINCT ?record) AS ?record_count) WHERE {
  VALUES ?prop { 
    wdt:P57 # director
    wdt:P58 # screenwriter
    wdt:P1877 # after a work by
  }
  ?record ?prop ?credit.
  ?record wdt:P31 ?p31.
  ?p31 schema:dateModified ?p31_updated
}
GROUP BY ?p31 ?p31_updated
ORDER BY DESC(?record_count)