SELECT ?p31 ?p31_updated (COUNT(DISTINCT ?record) AS ?record_count) WHERE {
  VALUES ?prop { 
    wdt:P1809 # choreographer
    wdt:P86 # composer
    wdt:P2515 # costume designer
    wdt:P12617 # creative director
    wdt:P3092 # film crew
    wdt:P1040 # film editor
    wdt:P2554 # production designer
    wdt:P5028 # sound designer
    wdt:P344 # director of photography / cinematographer
    wdt:P1431 # executive producer
    wdt:P162 # producer
  }
  ?record ?prop ?credit.
  ?record wdt:P31 ?p31.
  ?p31 schema:dateModified ?p31_updated.

  FILTER(xsd:integer(STRAFTER(STR(?record), "Q")) < 10000000)
}
GROUP BY ?p31 ?p31_updated
ORDER BY DESC(?record_count)