SELECT ?p31 ?p31_updated (COUNT(DISTINCT ?record) AS ?record_count) WHERE {
  VALUES ?prop { 
    wdt:P750 # distributed by
    wdt:P272 # production company
  }
  ?content ?prop ?record.
  ?record wdt:P31 ?p31.
  ?p31 schema:dateModified ?p31_updated.

  FILTER(xsd:integer(STRAFTER(STR(?record), "Q")) >= 10000000)
}
GROUP BY ?p31 ?p31_updated
ORDER BY DESC(?record_count)