SELECT ?nominee ?nominee_updated ?award ?award_updated WHERE {
  ?nominee wdt:P1411 ?award;
    schema:dateModified ?nominee_updated.
  ?award schema:dateModified ?award_updated.

  BIND(xsd:integer(STRAFTER(STR(?nominee), "Q")) AS ?qnum)
  FILTER(?qnum >= 10000000)
}