SELECT ?p31 ?p31_updated (COUNT(DISTINCT ?nominee) AS ?nominee_count) WHERE {
  ?nominee wdt:P1411 ?award.
  ?award wdt:P31 ?p31.
  ?p31 schema:dateModified ?p31_updated.
}
GROUP BY ?p31 ?p31_updated
ORDER BY DESC(?nominee_count)