SELECT ?prop ?p106 ?p106_updated (COUNT(DISTINCT ?credit) AS ?credit_count) WHERE {
  VALUES ?prop { 
    wdt:P161
  }
  FILTER (STR(?content) < "http://www.wikidata.org/entity/Q3000000")
  ?content ?prop ?credit.
  ?credit wdt:P106 ?p106.
  ?p106 schema:dateModified ?p106_updated
}
GROUP BY ?prop ?p106 ?p106_updated
ORDER BY ?prop DESC(?credit_count)