SELECT ?prop ?p106 ?p106_updated (COUNT(DISTINCT ?credit) AS ?credit_count) WHERE {
  VALUES ?prop { 
    wdt:P725 # voice actor
    wdt:P10606 # notable role
    wdt:P11108 # recorded participant
  }
  ?content ?prop ?credit.
  ?credit wdt:P106 ?p106.
  ?p106 schema:dateModified ?p106_updated
}
GROUP BY ?prop ?p106 ?p106_updated
ORDER BY ?prop DESC(?credit_count)